language: java
script: gradle copyJar
before_script:
  - git config --global user.name tryIO
  - git config --global user.email io.trydent@gmail.com
  #- git remote add origin https://github.com/trydent-io/proteus.git
after_script:
  - git commit -m 'Travis CI build' -a
  - git push origin master
jdk:
  - oraclejdk8
deploy:
  provider: openshift
  user: io.trydent@gmail.com
  password:
    secure: FjMcNQvLuyVS/p3V53fqQMMtXFyjQl1PsLirpIakm/66yTwPB/yyGEzO1lhRFSef3tkEtxcR5ylK08b082eKn1OucmMdJEdyPVL4ZLkqmGjU990bB4WuRz3NCiRRgPIp/xRLCkw24iFeUAw6XbbdbXxg5sInqypD8DsUd54vnHE=
  app: proteus
  domain: trydent
  on:
    repo: trydent-io/proteus
