language: java
script: gradle check & gradle jar
jdk:
- oraclejdk8
deploy:
  provider: openshift
  user: io.trydent@gmail.com
  password:
    secure: FjMcNQvLuyVS/p3V53fqQMMtXFyjQl1PsLirpIakm/66yTwPB/yyGEzO1lhRFSef3tkEtxcR5ylK08b082eKn1OucmMdJEdyPVL4ZLkqmGjU990bB4WuRz3NCiRRgPIp/xRLCkw24iFeUAw6XbbdbXxg5sInqypD8DsUd54vnHE=
  app: proteus
  domain: trydent
  on:
    repo: trydent-io/proteus
