spring.profiles.active: ${PROTEUS_PROFILE:dev}

spring:
  thymeleaf:
    mode:               HTML5
  jpa:
    hibernate:
      ddl-auto:         create

---

spring:
  profiles:             dev
dev:
  mysql:
    host:               127.0.0.1
    port:               3306
    schema:             proteus
    username:           root
    password:           piramide

---

spring:
  profiles:             build
build:
  hsql:
    host:               127.0.0.1
    port:               1234
    schema:             proteus
    username:           sa
    password:

---

spring:
  profiles:             openshift
server:
  address:              ${OPENSHIFT_DIY_IP:}
  port:                 ${OPENSHIFT_DIY_PORT:}
openshift:
  mysql:
    host:               ${OPENSHIFT_MYSQL_DB_HOST:}
    port:               ${OPENSHIFT_MYSQL_DB_PORT:}
    schema:             ${OPENSHIFT_APP_NAME:}
    username:           ${OPENSHIFT_MYSQL_DB_USERNAME:}
    password:           ${OPENSHIFT_MYSQL_DB_PASSWORD:}

---

spring:
  profiles:             heavy
server:
  address:              127.0.0.1
  port:                 1234
heavy:
  oracle:
    host:               127.0.0.1
    port:               1521
    database:           demo
    username:           demo
    password:           demo

---